# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BUET CSE Moodle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BUET CSE Moodle
  pod 'Alamofire', '~> 5.2'
end
